### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by u01jmg3** [u01jmg3/websql-json#1]
- [ ] Fix `this.queryInsert` & `this.queryValuesInsert` not being cleared after an `insert`
- [ ] Do not insert duplicate column data
- [ ] If the table already exists on `create`, do not show success message
- [ ] If no rows are affected on `update`, do not show success message
- [ ] Allow multiple tables to be passed into `delete`
